apiVersion: v1
kind: Service
metadata:
  name: dsirona-engine-ag-03
spec:
  type: NodePort
  ports:
  - name: ws
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: dsirona-engine-ag-03